Repository galilee-solana/depo, pull requests merged in 2025-04, with the labels that each got.

#16 Chore/redo add core states
  anchor/programs/depo/src/constants.rs
  anchor/programs/depo/src/errors.rs
  anchor/programs/depo/src/errors/mod.rs
  anchor/programs/depo/src/state/depositor.rs
  anchor/programs/depo/src/state/escrow.rs
  anchor/programs/depo/src/state/mod.rs
  anchor/programs/depo/src/state/module_type.rs
  anchor/programs/depo/src/state/modules/expiry_fallback.rs
  anchor/programs/depo/src/state/modules/minimum_amount.rs
  anchor/programs/depo/src/state/modules/mod.rs
  anchor/programs/depo/src/state/modules/module_type.rs
  anchor/programs/depo/src/state/modules/multisig_approval.rs
  anchor/programs/depo/src/state/modules/single_approval.rs
  anchor/programs/depo/src/state/modules/target_amount.rs
  anchor/programs/depo/src/state/modules/timelock.rs
  anchor/programs/depo/src/state/recipient.rs
  anchor/programs/depo/src/states/depositor.rs
  anchor/programs/depo/src/states/escrow.rs
  anchor/programs/depo/src/states/mod.rs
  anchor/programs/depo/src/states/modules/expiry_fallback.rs
  anchor/programs/depo/src/states/modules/minimum_amount.rs
  anchor/programs/depo/src/states/modules/mod.rs
  anchor/programs/depo/src/states/modules/module_type.rs
  anchor/programs/depo/src/states/modules/multisig_approval.rs
  anchor/programs/depo/src/states/modules/single_approval.rs
  anchor/programs/depo/src/states/modules/target_amount.rs
  anchor/programs/depo/src/states/modules/timelock.rs
  anchor/programs/depo/src/states/recipient.rs
  anchor/programs/depo/src/states/status.rs
Labels: smart contract

#34 Chore/create escrow
  anchor/programs/depo/src/accounts/add_depositor.rs
  anchor/programs/depo/src/accounts/add_recipient.rs
  anchor/programs/depo/src/accounts/cancel_escrow.rs
  anchor/programs/depo/src/accounts/create_escrow.rs
  anchor/programs/depo/src/accounts/deposit_escrow.rs
  anchor/programs/depo/src/accounts/mod.rs
  anchor/programs/depo/src/accounts/release_escrow.rs
  anchor/programs/depo/src/accounts/remove_depositor.rs
  anchor/programs/depo/src/accounts/remove_recipient.rs
  anchor/programs/depo/src/accounts/sign_approval.rs
  anchor/programs/depo/src/accounts/withdraw_escrow.rs
  anchor/programs/depo/src/constants.rs
  anchor/programs/depo/src/errors/escrow_errors.rs
  anchor/programs/depo/src/errors/general_errors.rs
  anchor/programs/depo/src/errors/mod.rs
  anchor/programs/depo/src/instructions/create_escrow.rs
  anchor/programs/depo/src/instructions/mod.rs
  anchor/programs/depo/src/lib.rs
  anchor/programs/depo/src/states/escrow.rs
  anchor/programs/depo/src/states/mod.rs
  anchor/programs/depo/src/states/modules/mod.rs
  anchor/programs/depo/src/utils/mod.rs
  anchor/programs/depo/src/utils/vec_to_fixed_size.rs
  anchor/src/depo-exports.ts
  anchor/target/idl/depo.json
  anchor/target/types/depo.ts
  anchor/tests/create_escrow_test.spec.ts
  anchor/tests/deposit.spec.ts
  package.json
  pnpm-lock.yaml
Labels: smart contract

#37 Dashboard styling
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/D-logo-black.svg
  public/D-logo-white.svg
  src/app/create/page.tsx
  src/app/deposit/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/account/account-data-access.tsx
  src/components/cluster/cluster-ui.tsx
  src/components/create/CreateButton.tsx
  src/components/create/CreateEscrowForm.tsx
  src/components/dashboard/dashboard-feature.tsx
  src/components/escrowcard/EscrowCard.tsx
  src/components/find/FindButton.tsx
  src/components/ui/ui-layout.tsx
  tailwind.config.ts
  tsconfig.json
Labels: front

#39 Chore/add remove recipient
  anchor/programs/depo/src/errors/escrow_errors.rs
  anchor/programs/depo/src/instructions/add_recipient.rs
  anchor/programs/depo/src/instructions/create_escrow.rs
  anchor/programs/depo/src/instructions/mod.rs
  anchor/programs/depo/src/instructions/remove_recipient.rs
  anchor/programs/depo/src/lib.rs
  anchor/programs/depo/src/states/escrow.rs
  anchor/programs/depo/src/states/status.rs
  anchor/target/idl/depo.json
  anchor/target/types/depo.ts
  anchor/tests/add_recipient_test.spec.ts
  anchor/tests/create_escrow_test.spec.ts
  anchor/tests/remove_recipient_test.spec.ts
Labels: smart contract

#45 feat: add/remove depositor
  anchor/programs/depo/src/errors/escrow_errors.rs
  anchor/programs/depo/src/instructions/add_depositor.rs
  anchor/programs/depo/src/instructions/add_recipient.rs
  anchor/programs/depo/src/instructions/mod.rs
  anchor/programs/depo/src/instructions/remove_depositor.rs
  anchor/programs/depo/src/instructions/remove_recipient.rs
  anchor/programs/depo/src/lib.rs
  anchor/programs/depo/src/states/mod.rs
  anchor/target/idl/depo.json
  anchor/target/types/depo.ts
  anchor/tests/add_depositor_test.spec.ts
  anchor/tests/remove_depositor_test.spec.ts
Labels: smart contract

#52 Create page
  src/app/create/page.tsx
  src/app/escrow/create/add_options/add_description/page.tsx
  src/app/escrow/create/add_options/add_multisig_approval/page.tsx
  src/app/escrow/create/add_options/add_single_approval/page.tsx
  src/app/escrow/create/add_options/page.tsx
  src/app/escrow/create/page.tsx
  src/app/escrow/create/set_depositor_address/page.tsx
  src/app/escrow/create/set_recipient_address/page.tsx
  src/app/escrow/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/create/CreateButton.tsx
  src/components/create/ToogleInputFieldDateTime.tsx
  src/components/create/ToogleInputFieldNumber.tsx
  src/components/create/ToogleInputFieldSolAddress.tsx
  src/components/create/ToogleInputLink.tsx
  src/components/ui/ui-layout.tsx
Labels: front

#50 Feat/release validation
  anchor/programs/depo/src/errors/general_errors.rs
  anchor/programs/depo/src/errors/mod.rs
  anchor/programs/depo/src/errors/release_errors.rs
  anchor/programs/depo/src/instructions/add_minimum_amount.rs
  anchor/programs/depo/src/instructions/release_escrow.rs
  anchor/programs/depo/src/instructions/remove_minimum_amount.rs
  anchor/programs/depo/src/lib.rs
  anchor/programs/depo/src/states/escrow.rs
  anchor/programs/depo/src/states/mod.rs
  anchor/programs/depo/src/states/modules/condition.rs
  anchor/programs/depo/src/states/modules/minimum_amount.rs
  anchor/programs/depo/src/states/modules/mod.rs
  anchor/programs/depo/src/states/modules/module_parser.rs
  anchor/programs/depo/src/states/modules/module_reference.rs
  anchor/programs/depo/src/states/validation.rs
  anchor/target/idl/depo.json
  anchor/target/types/depo.ts
  anchor/tests/add_minimum_amount_test.spec.ts
  anchor/tests/add_recipient_test.spec.ts
  anchor/tests/release_escrow_test.spec.ts
  anchor/tests/withdraw_escrow_test.spec.ts
  package.json
Labels: smart contract

#58 Chore/update readme
  .gitignore
  README.md
Labels: documentation

#64 Confirm create
  package-lock.json
  src/app/escrow/create/page.tsx
  src/app/layout.tsx
  src/components/ConfirmEscrow.tsx
  src/components/account/account-data-access.tsx
  src/components/account/account-ui.tsx
  src/components/confirmescrow/ConfirmEscrow.tsx
  src/components/create/CreateButton.tsx
  src/components/escrow_list/EscrowList.tsx
  src/components/ui/TransactionToast.tsx
  src/components/ui/ui-layout.tsx
  src/utils/utils.tsx
Labels: front
